// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-zuWqU2dgchuUelNmHLbyNDSFGdqL1y0',
    appId: '1:179973781771:web:80f5327ac71a40626eca0e',
    messagingSenderId: '179973781771',
    projectId: 'chat-app-ee270',
    authDomain: 'chat-app-ee270.firebaseapp.com',
    storageBucket: 'chat-app-ee270.firebasestorage.app',
    measurementId: 'G-F70RHWMBHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP6g7SdQCGJWjU0VMRXMPG7T5jcK145Vk',
    appId: '1:179973781771:android:bb092b0b95e1d7f76eca0e',
    messagingSenderId: '179973781771',
    projectId: 'chat-app-ee270',
    storageBucket: 'chat-app-ee270.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5iJ1eBCMhjvAHcFWW_ughRp_dDSx8p4g',
    appId: '1:179973781771:ios:dda7f3dfa4140f446eca0e',
    messagingSenderId: '179973781771',
    projectId: 'chat-app-ee270',
    storageBucket: 'chat-app-ee270.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5iJ1eBCMhjvAHcFWW_ughRp_dDSx8p4g',
    appId: '1:179973781771:ios:dda7f3dfa4140f446eca0e',
    messagingSenderId: '179973781771',
    projectId: 'chat-app-ee270',
    storageBucket: 'chat-app-ee270.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-zuWqU2dgchuUelNmHLbyNDSFGdqL1y0',
    appId: '1:179973781771:web:00c42c69d9a593476eca0e',
    messagingSenderId: '179973781771',
    projectId: 'chat-app-ee270',
    authDomain: 'chat-app-ee270.firebaseapp.com',
    storageBucket: 'chat-app-ee270.firebasestorage.app',
    measurementId: 'G-NMNF9P2N7D',
  );
}
